### PR TITLE
Add support to ALE (Asynchronous Lint Engine)

### PR DESCRIPTION
**Pull request by rafaelrinaldi**
This PR adds support to [ALE (Asynchronous Lint Engine)](https://github.com/w0rp/ale).

Before:
screen shot 2017-04-03 at 8 08 11 pm

After:
screen shot 2017-04-03 at 8 07 46 pm

### CODE REVIEW

**Comment by junegunn** [comment]
Are the screenshots correct? I can't see the difference.
By the way, please keep trailing spaces at line 400.

**Comment by rafaelrinaldi** [comment]
@junegunn If you take a closer look you'll notice the background for the linter bullets are wrong in the first screenshot (before) and correct on the second one (after).

Ps.: Just submitted a commit to preserve the whitespace as you requested.

**Comment by junegunn** [comment]
Ah, I see. I actually think that slightly darker background color is okay as it makes the signs easier to spot.

screen shot 2017-04-04 at 12 01 16 pm

But since `ALEErrorSign` (maps to `Error`) and `ALEWarningSign` (maps to `Todo`) are inconsistent, I don't object the change.

The patch changes the foreground colors to light green and blue which I think are not the best choices for warning and errors. How about this?

```vim
call s:hi('ALEErrorSign', [161, 161], [s:dark_bg + 1, s:light_bg - 2])
call s:hi('ALEWarningSign', [173, 173], [s:dark_bg + 1, s:light_bg - 2])
```

**Comment by rafaelrinaldi** [comment]
Works for me! I use Terminal.app so I was probably seeing different colors. The ones you suggested work great!

I've also added an EditorConfig file as I mentioned before to avoid problems for you in the future, let me know if you don't want to keep it.

**Comment by junegunn** [comment]
Thanks for the update. By the way I also experimented with the default background color and I seem to prefer this "no-spill" version.

```
call s:hi('ALEErrorSign', [161, 161], [s:dark_bg + 1, s:light_bg - 2])
call s:hi('ALEWarningSign', [174, 131], [s:dark_bg + 1, s:light_bg - 2])
```

screen shot 2017-04-05 at 10 12 15 am
screen shot 2017-04-05 at 10 12 11 am

```
call s:hi('ALEErrorSign', [161, 161], [s:dark_bg, s:light_bg])
call s:hi('ALEWarningSign', [174, 131], [s:dark_bg, s:light_bg])
```

screen shot 2017-04-05 at 10 11 44 am
screen shot 2017-04-05 at 10 11 23 am

What do you think? Note that I currently don't use vim-gitgutter (using vim-signify instead).

**Comment by rafaelrinaldi** [comment]
I like both to be honest, but would chose the first option since it looks more consistent when combined with `vim-gitgutter`.

**Comment by junegunn** [comment]
I'm personally leaning towards the latter, but the former is also okay. Consistency is nice, but on the other hand, maybe having distinct background colors for gitgutter (or signify which I currently use) and linter can be helpful to distinguish the two groups. I'm not sure though.

I'll merge this PR as it is now, and but I may change my mind later. Thanks.

**Comment by rafaelrinaldi** [comment]
To be honest, after trying the latter I can say I like it better haha. Feel free to change it if you want 👍 
Thanks for your feedback on this PR.

**Pull request merged**
