### PR TITLE
Add colorscheme for KDE (konsole, etc.)

### PR DESCRIPTION
**Pull request by ianks**
:arrow_up: :arrow_up: :arrow_up:

### CODE REVIEW

**Comment by junegunn** [comment]
Hi, I don't have KDE environment to test it, so, could you post the screenshot of [this script](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/tools/screenshotTable.sh)?

**Comment by ianks** [comment]
img

**Comment by junegunn** [comment]
Hmm, no, it doesn't look right. See the screenshots included in #18. I can't merge if it's not consistent with the other ones.

**Comment by ianks** [comment]
Looks like it did not save properly, here is the correct version.

Imgur

**Comment by junegunn** [comment]
Looks good. Thanks!

**Pull request merged**
