### PR TITLE
Add Terminal.app colorschemes

### PR DESCRIPTION
**Pull request by pgdouyon**
These should be identical to the iTerm2 themes.  Let me know if there are any problems!

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, but your schemes seem to use the same colors for bold and non-bold text, unlike iTerm2 versions.

This is how iTerm2 version looks like:
iterm2

And this is terminal.app version:
terminal app

Could you correct the colors so that they're equivalent to iTerm2 versions?
And this is just a minor preference thing, but I'd like the name of the directory to be `terminal-app` instead of `terminal_app`. :)

**Comment by pgdouyon** [comment]
lol I actually originally named the folder `terminal-app` but changed it because I thought I was the only one who preferred hyphens to underscores, I'll try to push out an update later tonight (which is in about 12 hours for me).

**Comment by pgdouyon** [comment]
Hi I've updated the color scheme to use bright colors for bold text.  I ran colortest.sh and everything seemed to check out, but I couldn't make out the colors for the cell (1m, 47m).  I'm not sure if it's a bug in the colorscheme or if my eyesight was just too bad to discern the difference.  I assumed the latter since all of the other bold colors seemed to render correctly.

**Comment by junegunn** [comment]
Thanks, the dark version looks fixed.

dark

But bold black on light version should be darker so that the text is readable on black background.

light

iTerm2 version:
iterm2-light

**Comment by junegunn** [comment]
@pgdouyon Any progress on this?

**Comment by pgdouyon** [comment]
ohhh wow so sorry this completely slipped my mind.  I'll take a look at it tonight, I'm not entirely sure why it's showing up like that but I'll figure something out.  Sorry for leaving this open for so long.

**Comment by junegunn** [comment]
No problem, there's no need to hurry at all.

**Comment by pgdouyon** [comment]
Sorry for the delay, I've updated the bold colors for both themes.  I ran the colortest script and couldn't find anything out of place, but let me know if there's still something else you'd like me to tweak.

**Comment by junegunn** [comment]
:+1:

**Pull request merged**
